matchSubStringForLicensorCompany = "Licensor Company"
matchSubStringForLicenseeCompany = "Licensee Company"
matchSubStringForAgentCompany = "Agent Company"


roleLicensee = "Licensee Contact"
roleLicensor = "Licensor Contact"
roleAgent = "Agent Contact"
roleLicenseeRoyalty = "Licensee Royalty Contact"

sheetNameForContact = "AddContacts"
sheetNameForCompany = "AddCompany"
sheetNameForIP = "AddIP"
sheetNameForProduct = "AddProduct"
sheetNameForLogin = "LoginData"
sheetNameForTestConfig = "testConfig"
sheetNameForCatalog = "addCatalog"
sheetNameForReceivables = "Receivables"

id = "167"
name = "Company"
ipName = "167 IP"
ipPrimaryId = "167 Primary ID"
productName = "167 Product"
categoryName = "167 Category"
primaryNumber = "167 Product"
categoryDesc = "167 Category"
linkedToProduct = "167 Product"
subCategoryName = "167 Sub Category"
subCategoryDesc = "167 Sub Category"
linkedToCat = "167 Category"
articleName = "167 Article"
articleDesc = "167 Article"
linkedTosubCat = "167 Sub Category"
lastNameContactLicensor = "Licensor"
lastNameContactLicensee = "Licensee"
lastNameContactLicenseeRoyalty = "Licensee"
lastNameContactAgent = "Agent"